spring:
  application:
    name: consumer
  cloud:
    function:
      definition: receiveRiderLocation;receiveRiderDeliveryStatus
    stream:
      function:
        definition: receiveRiderLocation;receiveRiderDeliveryStatus
      bindings:
        receiveRiderLocation-in-0:
#          destination: rider-location-topic
          destination: new-topic
          group: rider-group-v5 # Changed group to skip old "bad" data
          content-type: application/json
        receiveRiderDeliveryStatus-in-0:
#          destination: rider-location-topic
          destination: order-placed
          group: rider-group-status # Changed group to skip old "bad" data
          content-type: text/plain
      kafka:
        binder:
          brokers: localhost:9092
          configuration:
            # Force the consumer to use the local class regardless of what
            # package name the producer sent in the headers
            spring.json.use.type.headers: false
            spring.json.value.default.type: com.example.model.RiderLocation
            spring.json.trusted.packages: "*"
            # We use ByteArray because Spring Cloud Stream's MessageConverter
            # takes the bytes and does the JSON mapping itself.
            key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value.deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer

# Essential to avoid "Header" type mismatches
# (Where producer says it's a String, but consumer wants RiderLocation)
spring.cloud.stream.override-cloud-connectors: true

server:
  port: 8082