spring:
  application:
    name: consumer
  cloud:
    function:
      definition: getRiderLocation
    stream:
      function:
        definition: getRiderLocation
      bindings:
        getRiderLocation-in-0:
          destination: rider-location-topic
          content-type: application/json        # ✅ tells SCS to convert JSON → object
          consumer:
            max-attempts: 1
      kafka:
        binder:
          brokers: localhost:9092
          configuration:
            key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value.deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
#  kafka:
#    bootstrap-servers: localhost:9092
#    consumer:
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
#      properties:
#        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
#        spring.json.trusted.packages: "*"
#        spring.json.value.default.type: com.consumer.service.dto.RiderLocation
#

#spring:
#  application:
#    name: consumer
#  cloud:
#    function:
#      definition: getRiderLocation
#    stream:
#      function:
#        definition: getRiderLocation
#      bindings:
#        getRiderLocation-in-0:
#          destination: rider-location-topic
#          consumer:
#            max-attempts: 1
#      kafka:
#        binder:
#          brokers: localhost:9092
server:
  port: 8081

