spring:
  application:
    name: eureka-service-registry
  cloud:
    inetutils:
      ignored-interfaces:
        - vEthernet.*
        - WSL.*
      default-hostname: localhost
      default-ip-address: 127.0.0.1

management:
  endpoint:
    shutdown:
      access: unrestricted
  endpoints:
    web:
      exposure:
        include: health,info,refresh,shutdown

eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false

server:
  port: 8761