spring:
  application:
    name: eureka-service-registry

management:
  endpoint:
    shutdown:
      access: unrestricted
  endpoints:
    web:
      exposure:
        include: health,info,refresh,shutdown

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

server:
  port: 8761