spring:
  application:
    name: order-service
#  cloud:
#    config:
#      label: main  # This must match the 'label' column in your MySQL table
  config:
    import: optional:configserver:http://localhost:8888
#  profiles:
#    active: dev
