package com.ecommerce.project.service;

import com.ecommerce.project.dtos.ProductDTO;
import com.ecommerce.project.exceptions.custom.ResourceNotFoundException;
import com.ecommerce.project.model.Category;
import com.ecommerce.project.model.Product;
import com.ecommerce.project.repository.CategoryRepository;
import com.ecommerce.project.repository.ProductRepository;
import org.modelmapper.ModelMapper;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
public class ProductServiceImpl implements ProductService {

    @Autowired
    private CategoryRepository categoryRepository;

    @Autowired
    private ProductRepository productRepository;

    @Autowired
    private ModelMapper modelMapper;

    @Override
    public ProductDTO addProduct(ProductDTO productDTO, Long categoryId) {
        Category category = categoryRepository.findById(categoryId).orElseThrow(() -> new ResourceNotFoundException(categoryId, "categoryId", "Category"));
        Product newProduct = modelMapper.map(productDTO, Product.class);
        newProduct.setCategory(category);
        newProduct.setImage("autoGeneratedImg.png");
        double specialPrice = newProduct.getPrice() - (newProduct.getPrice() * (newProduct.getDiscount() / 100));
        newProduct.setSpecialPrice(specialPrice);
        return modelMapper.map(productRepository.save(newProduct), ProductDTO.class);
    }
}
