spring:
  cloud:
    inetutils:
      ignored-interfaces:
        - vEthernet.*
        - WSL.*
      default-hostname: localhost
      default-ip-address: 127.0.0.1
#    gateway:
#      server:
#        webflux:
#          routes:
#            - id: eureka-registry-service
#              uri: http://localhost:8761
#              predicates:
#                - name: Path
#                  args:
#                    patterns: /eureka/main
#              filters:
#                - SetPath= /
#
#            - id: eureka-registry-service-static
#              uri: http://localhost:8761
#              predicates:
#                - name: Path
#                  args:
#                    patterns:
#                      - /eureka/**
#                      - /eureka
#                      - /lastn
#                      - /js/**
#                      - /css/**
#                      - /fonts/**
#                      - /images/**
#              filters:
#                - StripPrefix=1
#
#            - id: user-service
#              uri: lb://USER-SERVICE
#              predicates:
#                - name: Path
#                  args:
##                    patterns: /api/users/**
#                    patterns:
#                      - /users
#                      - /users/**
#              filters:
#                - name: RewritePath
#                  args:
#                    regexp: /users(?<segment>/.*)
#                    replacement: /api/users${segment}
#
#            - id: product-service
#              uri: lb://PRODUCT-SERVICE
#              predicates:
#                - name: Path
#                  args:
#                    patterns:
#                      - /products
#                      - /products/**
#              filters:
#                - name: RewritePath
#                  args:
#                    regexp: /products(?<segment>/.*)
#                    replacement: /api/products{segment}
#
#            - id: order-service-cart
#              uri: lb://ORDER-SERVICE
#              filters:
#                - name: RewritePath
#                  args:
#                    regexp: /cart(?<segment>/.*)
#                    replacement: /api/cart{segment}
#              predicates:
#                - name: Path
#                  args:
#                    patterns:
#                      - /cart
#                      - /cart/**
#
#            - id: order-service-orders
#              uri: lb://ORDER-SERVICE
#              filters:
#                - name: RewritePath
#                  args:
#                    regexp: /orders(?<segment>/.*)
#                    replacement: /api/orders{segment}
#              predicates:
#                - name: Path
#                  args:
#                    patterns:
#                      - /orders
#                      - /orders/**

#Actuator Endpoints
management:
endpoints:
  web:
    exposure:
      include: "*"
  endpoint:
    health:
      show-details: ALWAYS
    info:
      show-details: ALWAYS
  health:
    circuitbreakers:
      enabled: true
tracing:
  sampling:
    probability: 1.0


# Circuit Breaker
resilience4j:
  circuitbreaker:
    instances:
      commonCircuitBreakerService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        automaticTransitionFromOpenToHalfOpenEnabled: true
        slidingWindowType: count_based

eureka:
instance:
  prefer-ip-address: true
  ip-address: 127.0.0.1
  hostname: localhost

client:
  serviceUrl:
    defaultZone: http://localhost:8761/eureka/
  register-with-eureka: true
  fetch-registry: true

logging:
  level:
    root: info
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
    org.springframework.cloud.gateway: TRACE

server:
port: 8080