spring:
  cloud:
    inetutils:
      ignored-interfaces:
        - vEthernet.*
        - WSL.*
      default-hostname: localhost
      default-ip-address: 127.0.0.1
  datasource:
    url: jdbc:postgresql://localhost:5432/order
    username: kalidas
    password: kalidas@123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    host: ${RABBITMQ_HOST_URL:localhost}
    port: ${RABBITMQ_HOST_PORT:5672}
    username: ${RABBITMQ_HOST_USERNAME:guest}
    password: ${RABBITMQ_HOST_PASSWORD:guest}
    virtual-host: ${RABBITMQ_VHOST:guest}
    connection-timeout: 30000
    exchange:
      name: order.exchange
    queue:
      name: order.queue
    routing:
      key: order.tracking
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
#    exchange:
#      name: order.exchange
#    queue:
#      name: order.queue
#    routing:
#      key: order.tracking


server:
  port: 8083

app:
  message: "Order Service"

#Actuator Endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
    info:
      show-details: ALWAYS
  health:
    circuitbreakers:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
#  zipkin:
#    tracing:
#      endpoint: ${ZIPKIN_URL:http://zipkin:9411/api/v2/spans}


# Circuit Breaker

resilience4j:
  ratelimiter:
    instances:
      orderServiceRateLimiter:
        timeout-duration: 0s
        limit-refresh-period: 4s
        limit-for-period: 2
  retry:
    instances:
      retryBreaker:
        maxAttempts: 5
        waitDuration: 1s
  circuitbreaker:
    instances:
      productService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        automaticTransitionFromOpenToHalfOpenEnabled: true
        slidingWindowType: count_based

eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

logging:
  file:
    name: logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 5MB
      max-history: 7


# KEYCLOAK
#keycloak:
#  admin:
#    username: user
#    password: user
#    server-url: http://keycloak:8080
#    realm: ecom-app
#    client-id: admin-cli
#    client-uid: 74d31cf4-5808-43de-93e0-01a079063245